# Generated by Django 4.1.3 on 2022-11-16 05:02

import django.db.models.deletion
import versatileimagefield.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Banner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_name", models.CharField(default=True, max_length=100)),
                ("product_title", models.CharField(default=True, max_length=100)),
                (
                    "product_image",
                    versatileimagefield.fields.VersatileImageField(
                        upload_to="image/testimagemodel/", verbose_name="Image"
                    ),
                ),
                ("product_price", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("blog_title", models.CharField(max_length=100)),
                (
                    "blog_image",
                    versatileimagefield.fields.VersatileImageField(
                        upload_to="image/testimagemodel/", verbose_name="Image"
                    ),
                ),
                (
                    "ppoi",
                    versatileimagefield.fields.PPOIField(
                        default="0.5x0.5",
                        editable=False,
                        max_length=20,
                        verbose_name="Image PPOI",
                    ),
                ),
                ("blog_content", models.CharField(max_length=200)),
                ("blogger_name", models.CharField(max_length=100)),
                (
                    "blogger_image",
                    versatileimagefield.fields.VersatileImageField(
                        upload_to="image/testimagemodel/", verbose_name="Image"
                    ),
                ),
                ("blog_date", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category_name", models.CharField(max_length=100)),
                (
                    "category_image",
                    versatileimagefield.fields.VersatileImageField(
                        upload_to="image/testimagemodel/", verbose_name="Image"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SpecialOffer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("offer_title", models.CharField(max_length=100)),
                (
                    "product_image",
                    versatileimagefield.fields.VersatileImageField(
                        upload_to="image/testimagemodel/", verbose_name="Image"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SubCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sub_category_name", models.CharField(max_length=100)),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="web.category",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_name", models.CharField(max_length=100)),
                ("product_price", models.IntegerField()),
                ("product_old_price", models.IntegerField()),
                (
                    "product_image",
                    versatileimagefield.fields.VersatileImageField(
                        upload_to="image/testimagemodel/", verbose_name="Image"
                    ),
                ),
                ("product_off", models.IntegerField()),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="web.category",
                    ),
                ),
                (
                    "sub_category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="web.subcategory",
                    ),
                ),
            ],
        ),
    ]
