# Generated by Django 4.1.3 on 2022-11-16 05:37

import versatileimagefield.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0002_team"),
    ]

    operations = [
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=100)),
                (
                    "user_image",
                    versatileimagefield.fields.VersatileImageField(
                        upload_to="image/testimagemodel/", verbose_name="Image"
                    ),
                ),
                ("user_role", models.CharField(max_length=100)),
                ("feedback", models.CharField(max_length=500)),
            ],
        ),
    ]
