# Generated by Django 4.1.3 on 2022-11-16 06:05

import versatileimagefield.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0003_feedback"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ad_image",
                    versatileimagefield.fields.VersatileImageField(
                        upload_to="image/testimagemodel/", verbose_name="Image"
                    ),
                ),
                ("ad_product_name", models.CharField(max_length=100)),
                ("ad_title", models.CharField(max_length=100)),
                ("offer_title", models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name="product",
            name="ppoi",
            field=versatileimagefield.fields.PPOIField(
                default="0.5x0.5",
                editable=False,
                max_length=20,
                verbose_name="Image PPOI",
            ),
        ),
    ]
